### PR TITLE
fix(client): use correct length for fwmarks

### LINKED ISSUE #1: Adding new service with FWMark fails
Trying to add/get service with FWMark fails:

Example:
```
func TestAddServiceFWM(t *testing.T) {
	cli, err := newClient()
	if err != nil {
		t.Fatalf(err.Error())
	}
	err = cli.CreateService(Service{
		Address:NewIP(net.ParseIP("0.0.0.0")),
		Port: 0,
		Scheduler: "rr",
		FWMark: 300,
	})

	if err != nil {
		t.Fatalf(err.Error())
	}
}

go test -run TestAddServiceFWM
--- FAIL: TestAddServiceFWM (0.00s)
    client_linux_test.go:372: netlink receive: invalid argument
FAIL
exit status 1
FAIL	github.com/cloudflare/ipvs	0.006s
```
Error seen in dmesg:
```
[Fri Sep 11 12:53:07 2020] netlink: 'ipvs.test': attribute type 5 has an invalid length.
```

Linux kernel version: 5.4.0

### PR DESCRIPTION
**Pull request by terinjokes**
Corrects the length of the fwmark attribute, which should be uint32
instead of uint16.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/netfilter/ipvs/ip_vs_ctl.c?h=v5.10#n2974

Fixes #1

### CODE REVIEW

File: client_linux_test.go [hunk 1]
```diff
@@ -316,38 +316,3 @@ func TestUnpackServiceCrashers(t *testing.T) {
 		_ = unpackService(&svc)([]byte(crash))
 	}
 }
-
-func TestServiceRoundTrip(t *testing.T) {
```
Comment (cbroglie) [inline client_linux_test.go:320]: What's the reason for removing this test?

And what do you think about adding the test from #1?

Comment (terinjokes) [reply client_linux_test.go:320]: It no longer parses because the size of the type changed.

I might add the test from #1 in a larger change that adds a separate suite that actually calls into a virtualized kernel.

**Review by cbroglie — APPROVED** [review]

**Review by pims — APPROVED** [review]
